pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - '#approved-reviews-by>=1'
    actions:
      merge:
        method: merge
