name: publish
on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry run
        type: boolean
      lerna-options:
        description: Lerna publish options

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: .nvmrc
          registry-url: 'https://registry.npmjs.org'

      - name: Configure Git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Lint commit message
        run: npx commitlint --from=HEAD~1

      - name: Build packages
        run: npm run build

      - name: Lint packages
        run: npm run lint

      - name: Test packages
        run: npm test

      - name: Publish (dry run)
        if: |
          github.ref_name == 'master'
          && github.event.inputs.dry-run == 'true'
        run: npx lerna version --no-git-tag-version --no-push --yes --loglevel=verbose

      - name: Publish canary
        if: |
          github.ref_name != 'master'
          && github.event.inputs.dry-run != 'true'
        run: npx lerna publish --canary --no-verify-access
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        if: |
          github.ref_name == 'master'
          && github.event.inputs.dry-run != 'true'
        run: npx lerna publish --no-verify-access
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
