name: scripts
on: push

jobs:
  scripts:
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: test_${{ github.run_id }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Create package
        run: |
          npm run create-package "${PACKAGE_NAME}_1"
          npm run create-package "@scope/${PACKAGE_NAME}_2" -- --template=typescript
          npm run create-package "${PACKAGE_NAME}_3" -- --template react

      - name: Lint created packages
        run: npx lerna run lint --scope="${PACKAGE_NAME}*"

      - name: Test created packages
        run: npx lerna run test --scope="${PACKAGE_NAME}*"
